# BLAS Backend Configuration
# ============================================================================
# Platform-specific auto-detection:
#   - macOS: Accelerate (system optimized)
#   - Linux: Try MKL > AOCL > OpenBLAS (in order of performance)
#   - Windows: Try MKL > OpenBLAS
# Users can override with explicit -DLAM_USE_* options
# ============================================================================

# Auto-detect available backends
set(_LAM_ACCELERATE_DEFAULT OFF)
set(_LAM_OPENBLAS_DEFAULT OFF)
set(_LAM_MKL_DEFAULT OFF)
set(_LAM_AOCL_DEFAULT OFF)

if(APPLE)
  set(_LAM_ACCELERATE_DEFAULT ON)
elseif(WIN32)
  # Windows: prefer MKL if available
  find_package(MKL QUIET CONFIG)
  if(MKL_FOUND)
    set(_LAM_MKL_DEFAULT ON)
  else()
    # Fallback: try generic BLAS (might find OpenBLAS)
    find_package(BLAS QUIET)
    if(BLAS_FOUND)
      set(_LAM_OPENBLAS_DEFAULT ON)
    endif()
  endif()
elseif(UNIX)  # Linux
  # Linux: try MKL first (best performance on Intel/AMD)
  find_package(MKL QUIET CONFIG)
  if(MKL_FOUND)
    set(_LAM_MKL_DEFAULT ON)
  else()
    # Try AMD AOCL (BLIS) - check for libblis
    find_library(BLIS_LIBRARY NAMES blis PATHS /opt/AMD/aocl/lib ENV AOCL_ROOT)
    if(BLIS_LIBRARY)
      set(_LAM_AOCL_DEFAULT ON)
    else()
      # Fallback: try generic BLAS (OpenBLAS)
      find_package(BLAS QUIET)
      if(BLAS_FOUND)
        set(_LAM_OPENBLAS_DEFAULT ON)
      endif()
    endif()
  endif()
endif()

option(LAM_USE_ACCELERATE "Use Apple Accelerate framework backend" ${_LAM_ACCELERATE_DEFAULT})
option(LAM_USE_MKL "Use Intel MKL backend" ${_LAM_MKL_DEFAULT})
option(LAM_USE_AOCL "Use AMD AOCL (BLIS) backend" ${_LAM_AOCL_DEFAULT})
option(LAM_USE_OPENBLAS "Use OpenBLAS backend" ${_LAM_OPENBLAS_DEFAULT})

# Determine active backend (priority: Accelerate > MKL > AOCL > OpenBLAS > None)
if(LAM_USE_ACCELERATE)
  set(LAM_USE_BLAS_BOOL "true")
  set(LAM_BLAS_BACKEND "accelerate")
elseif(LAM_USE_MKL)
  find_package(MKL REQUIRED CONFIG)
  set(LAM_USE_BLAS_BOOL "true")
  set(LAM_BLAS_BACKEND "mkl")
elseif(LAM_USE_AOCL)
  find_library(BLIS_LIBRARY NAMES blis REQUIRED PATHS /opt/AMD/aocl/lib ENV AOCL_ROOT)
  set(LAM_USE_BLAS_BOOL "true")
  set(LAM_BLAS_BACKEND "aocl")
elseif(LAM_USE_OPENBLAS)
  find_package(BLAS REQUIRED)
  set(LAM_USE_BLAS_BOOL "true")
  set(LAM_BLAS_BACKEND "openblas")
else()
  set(LAM_USE_BLAS_BOOL "false")
  set(LAM_BLAS_BACKEND "none")
endif()

# Function to link BLAS to a target
function(lam_link_blas target)
  if(LAM_USE_ACCELERATE)
    target_compile_definitions(${target} PUBLIC LAM_USE_BLAS ACCELERATE_NEW_LAPACK)
    target_link_libraries(${target} PUBLIC "-framework Accelerate")
    message(STATUS "${target}: Apple Accelerate backend enabled.")
  elseif(LAM_USE_MKL)
    target_compile_definitions(${target} PUBLIC LAM_USE_BLAS)
    target_link_libraries(${target} PUBLIC MKL::MKL)
    message(STATUS "${target}: Intel MKL backend enabled.")
  elseif(LAM_USE_AOCL)
    target_compile_definitions(${target} PUBLIC LAM_USE_BLAS)
    target_link_libraries(${target} PUBLIC ${BLIS_LIBRARY})
    message(STATUS "${target}: AMD AOCL (BLIS) backend enabled.")
  elseif(LAM_USE_OPENBLAS)
    target_compile_definitions(${target} PUBLIC LAM_USE_BLAS)
    target_link_libraries(${target} PUBLIC ${BLAS_LIBRARIES})
    message(STATUS "${target}: OpenBLAS backend enabled.")
  else()
    message(STATUS "${target}: No BLAS backend - using generic C++ fallback.")
  endif()
endfunction()
